#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CombatManagerDroid.Resource", IsApplication=true)]

namespace CombatManagerDroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int fadein = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int fadeout = 2130771969;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F020000
			public const int alignmentMode = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int columnCount = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int columnOrderPreserved = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int flChildSpacing = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int flChildSpacingForLastRow = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int flFlow = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int flMaxRows = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int flRowSpacing = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int flRtl = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int font = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int fontProviderAuthority = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int fontProviderCerts = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int fontProviderFetchStrategy = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int fontProviderFetchTimeout = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int fontProviderPackage = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int fontProviderQuery = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int fontStyle = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int fontWeight = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int layout_column = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int layout_columnSpan = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int layout_columnWeight = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int layout_gravity = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int layout_row = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int layout_rowSpan = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int layout_rowWeight = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int orientation = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int rowCount = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int rowOrderPreserved = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int useDefaultMargins = 2130837532;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7F030000
			public const int abc_action_bar_embed_tabs = 2130903040;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F04000F
			public const int default_color = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int main_tab_dark = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int main_tab_light = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int notification_action_color_filter = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int notification_icon_bg_color = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int notification_material_background_media_default_color = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int pressed_color = 2130968597;
			
			// aapt resource value: 0x7F040000
			public const int PrimaryColorDark = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int PrimaryColorDarker = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int PrimaryColorLight = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int PrimaryColorLighter = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int PrimaryColorMedium = 2130968580;
			
			// aapt resource value: 0x7F040016
			public const int primary_text_default_material_dark = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int ripple_material_light = 2130968599;
			
			// aapt resource value: 0x7F040005
			public const int SecondaryColorADark = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int SecondaryColorADarker = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int SecondaryColorALight = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int SecondaryColorALighter = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int SecondaryColorAMedium = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int SecondaryColorBDark = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int SecondaryColorBDarker = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int SecondaryColorBLight = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int SecondaryColorBLighter = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int SecondaryColorBMedium = 2130968590;
			
			// aapt resource value: 0x7F040018
			public const int secondary_text_default_material_dark = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int secondary_text_default_material_light = 2130968601;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F050000
			public const int compat_button_inset_horizontal_material = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int compat_button_inset_vertical_material = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int compat_button_padding_horizontal_material = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int compat_button_padding_vertical_material = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int compat_control_corner_material = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int default_gap = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int notification_action_icon_size = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int notification_action_text_size = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int notification_big_circle_margin = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int notification_content_margin_start = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int notification_large_icon_height = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int notification_large_icon_width = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int notification_main_column_padding_top = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int notification_media_narrow_margin = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int notification_right_icon_size = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int notification_right_side_padding_top = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int notification_small_icon_background_padding = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int notification_small_icon_size_as_large = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int notification_subtext_size = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int notification_top_pad = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int notification_top_pad_large_text = 2131034132;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F060000
			public const int ArrangeWindowsHS = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int arrowcurveleft16 = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int arrowcurveright16 = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int arrowdown16 = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int arrowsdown16 = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int arrowsup16 = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int arrowup16 = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int batterylow16 = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int bell16 = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int bg_key = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int bleeding16 = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int blind16 = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int blue_button = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int blue_button_inverse = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int book16 = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int book162x = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int bow16 = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int broken16 = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int brush16 = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int bulb16 = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int button2 = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int button_die = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int check16 = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int CheckBox = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int CheckBox2x = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int CheckBoxUnchecked = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int CheckBoxUnchecked2x = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int claw16 = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public const int clock16 = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int clone16 = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public const int coins16 = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public const int cower16 = 2131099679;
			
			// aapt resource value: 0x7F060020
			public const int d10016 = 2131099680;
			
			// aapt resource value: 0x7F060021
			public const int d100162x = 2131099681;
			
			// aapt resource value: 0x7F060022
			public const int d1016 = 2131099682;
			
			// aapt resource value: 0x7F060023
			public const int d10162x = 2131099683;
			
			// aapt resource value: 0x7F060024
			public const int d1216 = 2131099684;
			
			// aapt resource value: 0x7F060025
			public const int d12162x = 2131099685;
			
			// aapt resource value: 0x7F060026
			public const int d2016 = 2131099686;
			
			// aapt resource value: 0x7F060027
			public const int d2032 = 2131099687;
			
			// aapt resource value: 0x7F060028
			public const int d20322x = 2131099688;
			
			// aapt resource value: 0x7F060029
			public const int d2040 = 2131099689;
			
			// aapt resource value: 0x7F06002A
			public const int d20402x = 2131099690;
			
			// aapt resource value: 0x7F06002B
			public const int d20p16 = 2131099691;
			
			// aapt resource value: 0x7F06002C
			public const int d20p162x = 2131099692;
			
			// aapt resource value: 0x7F06002D
			public const int d416 = 2131099693;
			
			// aapt resource value: 0x7F06002E
			public const int d4162x = 2131099694;
			
			// aapt resource value: 0x7F06002F
			public const int d616 = 2131099695;
			
			// aapt resource value: 0x7F060030
			public const int d6162x = 2131099696;
			
			// aapt resource value: 0x7F060031
			public const int d816 = 2131099697;
			
			// aapt resource value: 0x7F060032
			public const int d8162x = 2131099698;
			
			// aapt resource value: 0x7F060033
			public const int dazed16 = 2131099699;
			
			// aapt resource value: 0x7F060034
			public const int dazzled16 = 2131099700;
			
			// aapt resource value: 0x7F060035
			public const int dead16 = 2131099701;
			
			// aapt resource value: 0x7F060036
			public const int deaf16 = 2131099702;
			
			// aapt resource value: 0x7F060037
			public const int delete16 = 2131099703;
			
			// aapt resource value: 0x7F060038
			public const int dice16 = 2131099704;
			
			// aapt resource value: 0x7F060039
			public const int DiePencil = 2131099705;
			
			// aapt resource value: 0x7F06003A
			public const int disease16 = 2131099706;
			
			// aapt resource value: 0x7F06003B
			public const int down16 = 2131099707;
			
			// aapt resource value: 0x7F06003C
			public const int ellipsis16 = 2131099708;
			
			// aapt resource value: 0x7F06003D
			public const int emerald16 = 2131099709;
			
			// aapt resource value: 0x7F06003E
			public const int exhausted16 = 2131099710;
			
			// aapt resource value: 0x7F06003F
			public const int facinated16 = 2131099711;
			
			// aapt resource value: 0x7F060040
			public const int fatigued16 = 2131099712;
			
			// aapt resource value: 0x7F060041
			public const int file16 = 2131099713;
			
			// aapt resource value: 0x7F060042
			public const int flagblue16 = 2131099714;
			
			// aapt resource value: 0x7F060043
			public const int flaggreen16 = 2131099715;
			
			// aapt resource value: 0x7F060044
			public const int flagred16 = 2131099716;
			
			// aapt resource value: 0x7F060045
			public const int folder16 = 2131099717;
			
			// aapt resource value: 0x7F060046
			public const int foot16 = 2131099718;
			
			// aapt resource value: 0x7F060047
			public const int gear2 = 2131099719;
			
			// aapt resource value: 0x7F060048
			public const int hand16 = 2131099720;
			
			// aapt resource value: 0x7F060049
			public const int handicapped16 = 2131099721;
			
			// aapt resource value: 0x7F06004A
			public const int hourglass16 = 2131099722;
			
			// aapt resource value: 0x7F06004C
			public const int Icon = 2131099724;
			
			// aapt resource value: 0x7F06004B
			public const int ic_sysbar_quicksettings = 2131099723;
			
			// aapt resource value: 0x7F06004D
			public const int import16 = 2131099725;
			
			// aapt resource value: 0x7F06004E
			public const int incorporeal16 = 2131099726;
			
			// aapt resource value: 0x7F06004F
			public const int info = 2131099727;
			
			// aapt resource value: 0x7F060050
			public const int info2x = 2131099728;
			
			// aapt resource value: 0x7F060051
			public const int init_button = 2131099729;
			
			// aapt resource value: 0x7F060052
			public const int invisible16 = 2131099730;
			
			// aapt resource value: 0x7F060053
			public const int keys16 = 2131099731;
			
			// aapt resource value: 0x7F060054
			public const int lasso16 = 2131099732;
			
			// aapt resource value: 0x7F060055
			public const int LeftArrow24 = 2131099733;
			
			// aapt resource value: 0x7F060056
			public const int LeftArrow242x = 2131099734;
			
			// aapt resource value: 0x7F060057
			public const int lightning16 = 2131099735;
			
			// aapt resource value: 0x7F060058
			public const int lightning162x = 2131099736;
			
			// aapt resource value: 0x7F060059
			public const int link16 = 2131099737;
			
			// aapt resource value: 0x7F06005A
			public const int lock16 = 2131099738;
			
			// aapt resource value: 0x7F06005B
			public const int magearmor16 = 2131099739;
			
			// aapt resource value: 0x7F06005C
			public const int mail16 = 2131099740;
			
			// aapt resource value: 0x7F06005D
			public const int mail162x = 2131099741;
			
			// aapt resource value: 0x7F06005E
			public const int main_tab = 2131099742;
			
			// aapt resource value: 0x7F06005F
			public const int main_tab_small = 2131099743;
			
			// aapt resource value: 0x7F060060
			public const int monster16 = 2131099744;
			
			// aapt resource value: 0x7F060061
			public const int nauseated16 = 2131099745;
			
			// aapt resource value: 0x7F060062
			public const int next16 = 2131099746;
			
			// aapt resource value: 0x7F060063
			public const int NoteHS = 2131099747;
			
			// aapt resource value: 0x7F060064
			public const int notes16 = 2131099748;
			
			// aapt resource value: 0x7F060065
			public const int notification_action_background = 2131099749;
			
			// aapt resource value: 0x7F060066
			public const int notification_bg = 2131099750;
			
			// aapt resource value: 0x7F060067
			public const int notification_bg_low = 2131099751;
			
			// aapt resource value: 0x7F060068
			public const int notification_bg_low_normal = 2131099752;
			
			// aapt resource value: 0x7F060069
			public const int notification_bg_low_pressed = 2131099753;
			
			// aapt resource value: 0x7F06006A
			public const int notification_bg_normal = 2131099754;
			
			// aapt resource value: 0x7F06006B
			public const int notification_bg_normal_pressed = 2131099755;
			
			// aapt resource value: 0x7F06006C
			public const int notification_icon_background = 2131099756;
			
			// aapt resource value: 0x7F06006D
			public const int notification_template_icon_bg = 2131099757;
			
			// aapt resource value: 0x7F06006E
			public const int notification_template_icon_low_bg = 2131099758;
			
			// aapt resource value: 0x7F06006F
			public const int notification_tile_bg = 2131099759;
			
			// aapt resource value: 0x7F060070
			public const int notify_panel_notification_icon_bg = 2131099760;
			
			// aapt resource value: 0x7F060071
			public const int openHS = 2131099761;
			
			// aapt resource value: 0x7F060072
			public const int openHS2x = 2131099762;
			
			// aapt resource value: 0x7F060073
			public const int panic16 = 2131099763;
			
			// aapt resource value: 0x7F060074
			public const int pencil16 = 2131099764;
			
			// aapt resource value: 0x7F060075
			public const int person16 = 2131099765;
			
			// aapt resource value: 0x7F060076
			public const int personwindow16 = 2131099766;
			
			// aapt resource value: 0x7F060077
			public const int pin16 = 2131099767;
			
			// aapt resource value: 0x7F060078
			public const int poison16 = 2131099768;
			
			// aapt resource value: 0x7F060079
			public const int prev16 = 2131099769;
			
			// aapt resource value: 0x7F06007A
			public const int PrintHS = 2131099770;
			
			// aapt resource value: 0x7F06007B
			public const int prone16 = 2131099771;
			
			// aapt resource value: 0x7F06007C
			public const int qm16 = 2131099772;
			
			// aapt resource value: 0x7F06007D
			public const int reaper16 = 2131099773;
			
			// aapt resource value: 0x7F06007E
			public const int redx = 2131099774;
			
			// aapt resource value: 0x7F06007F
			public const int redx2x = 2131099775;
			
			// aapt resource value: 0x7F060080
			public const int reset16 = 2131099776;
			
			// aapt resource value: 0x7F060081
			public const int RightArrow24 = 2131099777;
			
			// aapt resource value: 0x7F060082
			public const int RightArrow242x = 2131099778;
			
			// aapt resource value: 0x7F060083
			public const int rock16 = 2131099779;
			
			// aapt resource value: 0x7F060084
			public const int saveHS = 2131099780;
			
			// aapt resource value: 0x7F060085
			public const int saveHS2x = 2131099781;
			
			// aapt resource value: 0x7F060086
			public const int scared16 = 2131099782;
			
			// aapt resource value: 0x7F060087
			public const int screen16 = 2131099783;
			
			// aapt resource value: 0x7F060088
			public const int scroll16 = 2131099784;
			
			// aapt resource value: 0x7F060089
			public const int scrolleffect16 = 2131099785;
			
			// aapt resource value: 0x7F06008A
			public const int shaken16 = 2131099786;
			
			// aapt resource value: 0x7F06008B
			public const int sheet = 2131099787;
			
			// aapt resource value: 0x7F06008C
			public const int shield16 = 2131099788;
			
			// aapt resource value: 0x7F06008D
			public const int shielderror16 = 2131099789;
			
			// aapt resource value: 0x7F06008E
			public const int sick16 = 2131099790;
			
			// aapt resource value: 0x7F06008F
			public const int sleep16 = 2131099791;
			
			// aapt resource value: 0x7F060090
			public const int slow16 = 2131099792;
			
			// aapt resource value: 0x7F060091
			public const int sort16 = 2131099793;
			
			// aapt resource value: 0x7F060092
			public const int stable16 = 2131099794;
			
			// aapt resource value: 0x7F060093
			public const int star16 = 2131099795;
			
			// aapt resource value: 0x7F060094
			public const int star162x = 2131099796;
			
			// aapt resource value: 0x7F060095
			public const int stop16 = 2131099797;
			
			// aapt resource value: 0x7F060096
			public const int stunned16 = 2131099798;
			
			// aapt resource value: 0x7F060097
			public const int sword16 = 2131099799;
			
			// aapt resource value: 0x7F060098
			public const int swordsingle16 = 2131099800;
			
			// aapt resource value: 0x7F060099
			public const int target16 = 2131099801;
			
			// aapt resource value: 0x7F06009A
			public const int treasure16 = 2131099802;
			
			// aapt resource value: 0x7F06009B
			public const int treasure162x = 2131099803;
			
			// aapt resource value: 0x7F06009C
			public const int unlock16 = 2131099804;
			
			// aapt resource value: 0x7F06009D
			public const int wand16 = 2131099805;
			
			// aapt resource value: 0x7F06009E
			public const int zoomin16 = 2131099806;
			
			// aapt resource value: 0x7F06009F
			public const int zoomout16 = 2131099807;
			
			// aapt resource value: 0x7F0600A0
			public const int zzz16 = 2131099808;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F070000
			public const int acText = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int action0 = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int actionButton = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int actionListView = 2131165187;
			
			// aapt resource value: 0x7F070008
			public const int actions = 2131165192;
			
			// aapt resource value: 0x7F070004
			public const int action_container = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int action_divider = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int action_image = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int action_text = 2131165191;
			
			// aapt resource value: 0x7F070009
			public const int add10Button = 2131165193;
			
			// aapt resource value: 0x7F07000A
			public const int add12Button = 2131165194;
			
			// aapt resource value: 0x7F07000B
			public const int add20Button = 2131165195;
			
			// aapt resource value: 0x7F07000C
			public const int add4Button = 2131165196;
			
			// aapt resource value: 0x7F07000D
			public const int add6Button = 2131165197;
			
			// aapt resource value: 0x7F07000E
			public const int add8Button = 2131165198;
			
			// aapt resource value: 0x7F07000F
			public const int addButton = 2131165199;
			
			// aapt resource value: 0x7F070010
			public const int addMeleeButton = 2131165200;
			
			// aapt resource value: 0x7F070011
			public const int addNaturalButton = 2131165201;
			
			// aapt resource value: 0x7F070012
			public const int addRangedButton = 2131165202;
			
			// aapt resource value: 0x7F070013
			public const int addSpellLevelButton = 2131165203;
			
			// aapt resource value: 0x7F070014
			public const int advancedBox = 2131165204;
			
			// aapt resource value: 0x7F070015
			public const int advancedMultiplierButton = 2131165205;
			
			// aapt resource value: 0x7F070016
			public const int afflictionsButton = 2131165206;
			
			// aapt resource value: 0x7F070017
			public const int align = 2131165207;
			
			// aapt resource value: 0x7F070018
			public const int alignBounds = 2131165208;
			
			// aapt resource value: 0x7F070019
			public const int alignMargins = 2131165209;
			
			// aapt resource value: 0x7F07001A
			public const int alignmentButton = 2131165210;
			
			// aapt resource value: 0x7F07001B
			public const int areaButton = 2131165211;
			
			// aapt resource value: 0x7F07001C
			public const int armorText = 2131165212;
			
			// aapt resource value: 0x7F07001D
			public const int async = 2131165213;
			
			// aapt resource value: 0x7F07001E
			public const int attacksEditorButton = 2131165214;
			
			// aapt resource value: 0x7F07001F
			public const int augmentSummoningBox = 2131165215;
			
			// aapt resource value: 0x7F070020
			public const int auraText = 2131165216;
			
			// aapt resource value: 0x7F070021
			public const int auto = 2131165217;
			
			// aapt resource value: 0x7F070022
			public const int backButton = 2131165218;
			
			// aapt resource value: 0x7F070023
			public const int baseAttackText = 2131165219;
			
			// aapt resource value: 0x7F070024
			public const int basicLayout = 2131165220;
			
			// aapt resource value: 0x7F070025
			public const int beforeCombatText = 2131165221;
			
			// aapt resource value: 0x7F070026
			public const int benefitText = 2131165222;
			
			// aapt resource value: 0x7F070027
			public const int blankButton = 2131165223;
			
			// aapt resource value: 0x7F070028
			public const int blocking = 2131165224;
			
			// aapt resource value: 0x7F070029
			public const int bloodyBox = 2131165225;
			
			// aapt resource value: 0x7F07002A
			public const int bodyLayout = 2131165226;
			
			// aapt resource value: 0x7F07002B
			public const int bonusStatButton = 2131165227;
			
			// aapt resource value: 0x7F07002C
			public const int bottom = 2131165228;
			
			// aapt resource value: 0x7F07002D
			public const int bottomLayout = 2131165229;
			
			// aapt resource value: 0x7F07002E
			public const int burningBox = 2131165230;
			
			// aapt resource value: 0x7F07002F
			public const int burrowText = 2131165231;
			
			// aapt resource value: 0x7F070030
			public const int button1 = 2131165232;
			
			// aapt resource value: 0x7F070031
			public const int button2 = 2131165233;
			
			// aapt resource value: 0x7F070032
			public const int button3 = 2131165234;
			
			// aapt resource value: 0x7F070033
			public const int button4 = 2131165235;
			
			// aapt resource value: 0x7F070034
			public const int byItemsButton = 2131165236;
			
			// aapt resource value: 0x7F070035
			public const int byLevelButton = 2131165237;
			
			// aapt resource value: 0x7F070036
			public const int cancelButton = 2131165238;
			
			// aapt resource value: 0x7F070037
			public const int cancel_action = 2131165239;
			
			// aapt resource value: 0x7F070038
			public const int castingTimeButton = 2131165240;
			
			// aapt resource value: 0x7F070039
			public const int center = 2131165241;
			
			// aapt resource value: 0x7F07003A
			public const int center_horizontal = 2131165242;
			
			// aapt resource value: 0x7F07003B
			public const int center_vertical = 2131165243;
			
			// aapt resource value: 0x7F07003C
			public const int chaBox = 2131165244;
			
			// aapt resource value: 0x7F07003E
			public const int championBox = 2131165246;
			
			// aapt resource value: 0x7F07003F
			public const int characterList = 2131165247;
			
			// aapt resource value: 0x7F070040
			public const int characterText = 2131165248;
			
			// aapt resource value: 0x7F070041
			public const int characterView = 2131165249;
			
			// aapt resource value: 0x7F07003D
			public const int chaText = 2131165245;
			
			// aapt resource value: 0x7F070042
			public const int chronometer = 2131165250;
			
			// aapt resource value: 0x7F070043
			public const int classText = 2131165251;
			
			// aapt resource value: 0x7F070044
			public const int clearButton = 2131165252;
			
			// aapt resource value: 0x7F070045
			public const int clearInitiativeButton = 2131165253;
			
			// aapt resource value: 0x7F070046
			public const int clearRollButton = 2131165254;
			
			// aapt resource value: 0x7F070047
			public const int climbText = 2131165255;
			
			// aapt resource value: 0x7F070048
			public const int clip_horizontal = 2131165256;
			
			// aapt resource value: 0x7F070049
			public const int clip_vertical = 2131165257;
			
			// aapt resource value: 0x7F07004A
			public const int closeButton = 2131165258;
			
			// aapt resource value: 0x7F07004B
			public const int cmbText = 2131165259;
			
			// aapt resource value: 0x7F07004C
			public const int cmdText = 2131165260;
			
			// aapt resource value: 0x7F07004D
			public const int coinButton = 2131165261;
			
			// aapt resource value: 0x7F07004E
			public const int column1 = 2131165262;
			
			// aapt resource value: 0x7F07004F
			public const int column2 = 2131165263;
			
			// aapt resource value: 0x7F070050
			public const int column3 = 2131165264;
			
			// aapt resource value: 0x7F070051
			public const int column4 = 2131165265;
			
			// aapt resource value: 0x7F070052
			public const int combatButton = 2131165266;
			
			// aapt resource value: 0x7F070053
			public const int combatImageButton = 2131165267;
			
			// aapt resource value: 0x7F070054
			public const int combatListButton = 2131165268;
			
			// aapt resource value: 0x7F070055
			public const int combatListLayout = 2131165269;
			
			// aapt resource value: 0x7F070056
			public const int conBox = 2131165270;
			
			// aapt resource value: 0x7F070059
			public const int conditionsButton = 2131165273;
			
			// aapt resource value: 0x7F07005A
			public const int conditionsLayout = 2131165274;
			
			// aapt resource value: 0x7F07005B
			public const int conditionsTabButton = 2131165275;
			
			// aapt resource value: 0x7F070058
			public const int conditionView = 2131165272;
			
			// aapt resource value: 0x7F07005C
			public const int confirmBox = 2131165276;
			
			// aapt resource value: 0x7F070057
			public const int conText = 2131165271;
			
			// aapt resource value: 0x7F07005D
			public const int countButton = 2131165277;
			
			// aapt resource value: 0x7F07005E
			public const int crButton = 2131165278;
			
			// aapt resource value: 0x7F07005F
			public const int d10Text = 2131165279;
			
			// aapt resource value: 0x7F070060
			public const int d12Text = 2131165280;
			
			// aapt resource value: 0x7F070061
			public const int d20Text = 2131165281;
			
			// aapt resource value: 0x7F070062
			public const int d4Text = 2131165282;
			
			// aapt resource value: 0x7F070063
			public const int d6Text = 2131165283;
			
			// aapt resource value: 0x7F070064
			public const int d8Text = 2131165284;
			
			// aapt resource value: 0x7F070065
			public const int defAbilitiesText = 2131165285;
			
			// aapt resource value: 0x7F070066
			public const int defenseImageTab = 2131165286;
			
			// aapt resource value: 0x7F070067
			public const int defenseTab = 2131165287;
			
			// aapt resource value: 0x7F070068
			public const int deflectionText = 2131165288;
			
			// aapt resource value: 0x7F070069
			public const int deleteButton = 2131165289;
			
			// aapt resource value: 0x7F07006A
			public const int descriptionImageTab = 2131165290;
			
			// aapt resource value: 0x7F07006B
			public const int descriptionTab = 2131165291;
			
			// aapt resource value: 0x7F07006C
			public const int descriptionText = 2131165292;
			
			// aapt resource value: 0x7F07006D
			public const int descriptorButton = 2131165293;
			
			// aapt resource value: 0x7F07006E
			public const int dexBox = 2131165294;
			
			// aapt resource value: 0x7F07006F
			public const int dexText = 2131165295;
			
			// aapt resource value: 0x7F070070
			public const int dieRollerLayout = 2131165296;
			
			// aapt resource value: 0x7F070071
			public const int dismissibleCheckbox = 2131165297;
			
			// aapt resource value: 0x7F070072
			public const int divineFocusCheckbox = 2131165298;
			
			// aapt resource value: 0x7F070073
			public const int dodgeText = 2131165299;
			
			// aapt resource value: 0x7F070074
			public const int downButton = 2131165300;
			
			// aapt resource value: 0x7F070076
			public const int dragonColorButton = 2131165302;
			
			// aapt resource value: 0x7F070075
			public const int drText = 2131165301;
			
			// aapt resource value: 0x7F070077
			public const int durationButton = 2131165303;
			
			// aapt resource value: 0x7F070078
			public const int duringCombatText = 2131165304;
			
			// aapt resource value: 0x7F070079
			public const int end = 2131165305;
			
			// aapt resource value: 0x7F07007A
			public const int end_padder = 2131165306;
			
			// aapt resource value: 0x7F07007B
			public const int environmentText = 2131165307;
			
			// aapt resource value: 0x7F07007C
			public const int featsButton = 2131165308;
			
			// aapt resource value: 0x7F07007D
			public const int featsImageButton = 2131165309;
			
			// aapt resource value: 0x7F07007E
			public const int featsImageTab = 2131165310;
			
			// aapt resource value: 0x7F07007F
			public const int featsLayout = 2131165311;
			
			// aapt resource value: 0x7F070080
			public const int featsList = 2131165312;
			
			// aapt resource value: 0x7F070081
			public const int featsTab = 2131165313;
			
			// aapt resource value: 0x7F070082
			public const int featsTabButton = 2131165314;
			
			// aapt resource value: 0x7F070083
			public const int fileList = 2131165315;
			
			// aapt resource value: 0x7F070084
			public const int fileName = 2131165316;
			
			// aapt resource value: 0x7F070085
			public const int fill = 2131165317;
			
			// aapt resource value: 0x7F070086
			public const int fill_horizontal = 2131165318;
			
			// aapt resource value: 0x7F070087
			public const int fill_vertical = 2131165319;
			
			// aapt resource value: 0x7F070088
			public const int filterLayout = 2131165320;
			
			// aapt resource value: 0x7F070089
			public const int filterText = 2131165321;
			
			// aapt resource value: 0x7F07008A
			public const int flatFootedText = 2131165322;
			
			// aapt resource value: 0x7F07008B
			public const int flyQualityButton = 2131165323;
			
			// aapt resource value: 0x7F07008C
			public const int flyText = 2131165324;
			
			// aapt resource value: 0x7F07008D
			public const int focusCheckbox = 2131165325;
			
			// aapt resource value: 0x7F07008E
			public const int focusText = 2131165326;
			
			// aapt resource value: 0x7F07008F
			public const int folderNameText = 2131165327;
			
			// aapt resource value: 0x7F070090
			public const int folderUpButton = 2131165328;
			
			// aapt resource value: 0x7F070091
			public const int forever = 2131165329;
			
			// aapt resource value: 0x7F070092
			public const int fortText = 2131165330;
			
			// aapt resource value: 0x7F070093
			public const int gearText = 2131165331;
			
			// aapt resource value: 0x7F070094
			public const int generateItemsButton = 2131165332;
			
			// aapt resource value: 0x7F070095
			public const int generateLevelButton = 2131165333;
			
			// aapt resource value: 0x7F070096
			public const int goodsButton = 2131165334;
			
			// aapt resource value: 0x7F070097
			public const int hdButton = 2131165335;
			
			// aapt resource value: 0x7F070098
			public const int hdCountButton = 2131165336;
			
			// aapt resource value: 0x7F070099
			public const int hdLayout = 2131165337;
			
			// aapt resource value: 0x7F07009A
			public const int helpButton = 2131165338;
			
			// aapt resource value: 0x7F07009B
			public const int horizontal = 2131165339;
			
			// aapt resource value: 0x7F07009C
			public const int horizontalScrollView1 = 2131165340;
			
			// aapt resource value: 0x7F07009D
			public const int hpButton = 2131165341;
			
			// aapt resource value: 0x7F07009E
			public const int hpMaxButton = 2131165342;
			
			// aapt resource value: 0x7F07009F
			public const int hpModsText = 2131165343;
			
			// aapt resource value: 0x7F0700A0
			public const int hpText = 2131165344;
			
			// aapt resource value: 0x7F0700A1
			public const int icon = 2131165345;
			
			// aapt resource value: 0x7F0700A2
			public const int icon_group = 2131165346;
			
			// aapt resource value: 0x7F0700A3
			public const int imageView1 = 2131165347;
			
			// aapt resource value: 0x7F0700A4
			public const int imageView2 = 2131165348;
			
			// aapt resource value: 0x7F0700A5
			public const int imageView3 = 2131165349;
			
			// aapt resource value: 0x7F0700A6
			public const int immuneText = 2131165350;
			
			// aapt resource value: 0x7F0700A7
			public const int info = 2131165351;
			
			// aapt resource value: 0x7F0700A8
			public const int initButton = 2131165352;
			
			// aapt resource value: 0x7F0700AA
			public const int initiativeList = 2131165354;
			
			// aapt resource value: 0x7F0700A9
			public const int initText = 2131165353;
			
			// aapt resource value: 0x7F0700AB
			public const int intBox = 2131165355;
			
			// aapt resource value: 0x7F0700AC
			public const int intText = 2131165356;
			
			// aapt resource value: 0x7F0700AD
			public const int italic = 2131165357;
			
			// aapt resource value: 0x7F0700AE
			public const int itemCheckBox = 2131165358;
			
			// aapt resource value: 0x7F0700AF
			public const int itemList = 2131165359;
			
			// aapt resource value: 0x7F0700B0
			public const int itemListView = 2131165360;
			
			// aapt resource value: 0x7F0700B2
			public const int itemsLayout = 2131165362;
			
			// aapt resource value: 0x7F0700B3
			public const int itemsLevelButton = 2131165363;
			
			// aapt resource value: 0x7F0700B1
			public const int itemView = 2131165361;
			
			// aapt resource value: 0x7F0700B4
			public const int languagesText = 2131165364;
			
			// aapt resource value: 0x7F0700B5
			public const int left = 2131165365;
			
			// aapt resource value: 0x7F0700B6
			public const int leftLayout = 2131165366;
			
			// aapt resource value: 0x7F0700B7
			public const int levelButton = 2131165367;
			
			// aapt resource value: 0x7F0700B8
			public const int levelLayout = 2131165368;
			
			// aapt resource value: 0x7F0700B9
			public const int levelText = 2131165369;
			
			// aapt resource value: 0x7F0700BA
			public const int line1 = 2131165370;
			
			// aapt resource value: 0x7F0700BB
			public const int line3 = 2131165371;
			
			// aapt resource value: 0x7F0700BC
			public const int linearLayout1 = 2131165372;
			
			// aapt resource value: 0x7F0700BD
			public const int linearLayout10 = 2131165373;
			
			// aapt resource value: 0x7F0700BE
			public const int linearLayout101 = 2131165374;
			
			// aapt resource value: 0x7F0700BF
			public const int linearLayout103 = 2131165375;
			
			// aapt resource value: 0x7F0700C0
			public const int linearLayout106 = 2131165376;
			
			// aapt resource value: 0x7F0700C1
			public const int linearLayout11 = 2131165377;
			
			// aapt resource value: 0x7F0700C2
			public const int linearLayout125 = 2131165378;
			
			// aapt resource value: 0x7F0700C3
			public const int linearLayout13 = 2131165379;
			
			// aapt resource value: 0x7F0700C4
			public const int linearLayout14 = 2131165380;
			
			// aapt resource value: 0x7F0700C5
			public const int linearLayout15 = 2131165381;
			
			// aapt resource value: 0x7F0700C6
			public const int linearLayout16 = 2131165382;
			
			// aapt resource value: 0x7F0700C7
			public const int linearLayout2 = 2131165383;
			
			// aapt resource value: 0x7F0700C8
			public const int linearLayout3 = 2131165384;
			
			// aapt resource value: 0x7F0700C9
			public const int linearLayout4 = 2131165385;
			
			// aapt resource value: 0x7F0700CA
			public const int linearLayout5 = 2131165386;
			
			// aapt resource value: 0x7F0700CB
			public const int linearLayout6 = 2131165387;
			
			// aapt resource value: 0x7F0700CC
			public const int linearLayout7 = 2131165388;
			
			// aapt resource value: 0x7F0700CD
			public const int linearLayout8 = 2131165389;
			
			// aapt resource value: 0x7F0700CE
			public const int linearLayout9 = 2131165390;
			
			// aapt resource value: 0x7F0700CF
			public const int loadButton = 2131165391;
			
			// aapt resource value: 0x7F0700D1
			public const int magicalArmorBox = 2131165393;
			
			// aapt resource value: 0x7F0700D2
			public const int magicalWeaponBox = 2131165394;
			
			// aapt resource value: 0x7F0700D0
			public const int magicItemsButton = 2131165392;
			
			// aapt resource value: 0x7F0700D3
			public const int mainImageTab = 2131165395;
			
			// aapt resource value: 0x7F0700D4
			public const int mainTab = 2131165396;
			
			// aapt resource value: 0x7F0700D5
			public const int materialCheckbox = 2131165397;
			
			// aapt resource value: 0x7F0700D6
			public const int materialText = 2131165398;
			
			// aapt resource value: 0x7F0700D7
			public const int media_actions = 2131165399;
			
			// aapt resource value: 0x7F0700D8
			public const int meleeAttacksButton = 2131165400;
			
			// aapt resource value: 0x7F0700D9
			public const int meleeGroupLayout = 2131165401;
			
			// aapt resource value: 0x7F0700DA
			public const int meleeLayout = 2131165402;
			
			// aapt resource value: 0x7F0700DB
			public const int modText = 2131165403;
			
			// aapt resource value: 0x7F0700DC
			public const int monsterButton = 2131165404;
			
			// aapt resource value: 0x7F0700DD
			public const int monsterEditText = 2131165405;
			
			// aapt resource value: 0x7F0700DE
			public const int monsterListButton = 2131165406;
			
			// aapt resource value: 0x7F0700DF
			public const int monsterListLayout = 2131165407;
			
			// aapt resource value: 0x7F0700E0
			public const int monsterListView = 2131165408;
			
			// aapt resource value: 0x7F0700E1
			public const int monstersButton = 2131165409;
			
			// aapt resource value: 0x7F0700E2
			public const int monstersImageButton = 2131165410;
			
			// aapt resource value: 0x7F0700E3
			public const int monstersTabButton = 2131165411;
			
			// aapt resource value: 0x7F0700E4
			public const int moraleText = 2131165412;
			
			// aapt resource value: 0x7F0700E5
			public const int movementLayout = 2131165413;
			
			// aapt resource value: 0x7F0700E6
			public const int nameEditText = 2131165414;
			
			// aapt resource value: 0x7F0700E7
			public const int nameText = 2131165415;
			
			// aapt resource value: 0x7F0700E8
			public const int naturalLayout = 2131165416;
			
			// aapt resource value: 0x7F0700E9
			public const int naturalText = 2131165417;
			
			// aapt resource value: 0x7F0700EA
			public const int nextButton = 2131165418;
			
			// aapt resource value: 0x7F0700EB
			public const int normal = 2131165419;
			
			// aapt resource value: 0x7F0700EC
			public const int normalText = 2131165420;
			
			// aapt resource value: 0x7F0700ED
			public const int notification_background = 2131165421;
			
			// aapt resource value: 0x7F0700EE
			public const int notification_main_column = 2131165422;
			
			// aapt resource value: 0x7F0700EF
			public const int notification_main_column_container = 2131165423;
			
			// aapt resource value: 0x7F0700F0
			public const int offenseImageTab = 2131165424;
			
			// aapt resource value: 0x7F0700F1
			public const int offenseTab = 2131165425;
			
			// aapt resource value: 0x7F0700F2
			public const int okButton = 2131165426;
			
			// aapt resource value: 0x7F0700F3
			public const int organizationText = 2131165427;
			
			// aapt resource value: 0x7F0700F4
			public const int outsiderButton = 2131165428;
			
			// aapt resource value: 0x7F0700F5
			public const int playerListButton = 2131165429;
			
			// aapt resource value: 0x7F0700F6
			public const int playerListLayout = 2131165430;
			
			// aapt resource value: 0x7F0700F7
			public const int potionBox = 2131165431;
			
			// aapt resource value: 0x7F0700F8
			public const int prerequisitesText = 2131165432;
			
			// aapt resource value: 0x7F0700F9
			public const int prevButton = 2131165433;
			
			// aapt resource value: 0x7F0700FA
			public const int progressBar1 = 2131165434;
			
			// aapt resource value: 0x7F0700FB
			public const int raceText = 2131165435;
			
			// aapt resource value: 0x7F0700FC
			public const int racialModsText = 2131165436;
			
			// aapt resource value: 0x7F0700FD
			public const int rangeButton = 2131165437;
			
			// aapt resource value: 0x7F0700FE
			public const int rangedAttacksButton = 2131165438;
			
			// aapt resource value: 0x7F0700FF
			public const int rangedLayout = 2131165439;
			
			// aapt resource value: 0x7F070100
			public const int reachText = 2131165440;
			
			// aapt resource value: 0x7F070101
			public const int refText = 2131165441;
			
			// aapt resource value: 0x7F070102
			public const int relativeLayout1 = 2131165442;
			
			// aapt resource value: 0x7F070103
			public const int resetButton = 2131165443;
			
			// aapt resource value: 0x7F070104
			public const int resistText = 2131165444;
			
			// aapt resource value: 0x7F070105
			public const int right = 2131165445;
			
			// aapt resource value: 0x7F070106
			public const int right_icon = 2131165446;
			
			// aapt resource value: 0x7F070107
			public const int right_side = 2131165447;
			
			// aapt resource value: 0x7F070108
			public const int ringBox = 2131165448;
			
			// aapt resource value: 0x7F070109
			public const int rodBox = 2131165449;
			
			// aapt resource value: 0x7F07010A
			public const int roll3d6Box = 2131165450;
			
			// aapt resource value: 0x7F07010B
			public const int rollButton = 2131165451;
			
			// aapt resource value: 0x7F07010C
			public const int rollD100Button = 2131165452;
			
			// aapt resource value: 0x7F07010D
			public const int rollD10Button = 2131165453;
			
			// aapt resource value: 0x7F07010E
			public const int rollD12Button = 2131165454;
			
			// aapt resource value: 0x7F07010F
			public const int rollD20Button = 2131165455;
			
			// aapt resource value: 0x7F070110
			public const int rollD4Button = 2131165456;
			
			// aapt resource value: 0x7F070111
			public const int rollD6Button = 2131165457;
			
			// aapt resource value: 0x7F070112
			public const int rollD8Button = 2131165458;
			
			// aapt resource value: 0x7F070113
			public const int rollInitiativeButton = 2131165459;
			
			// aapt resource value: 0x7F070114
			public const int rollMonsterHPBox = 2131165460;
			
			// aapt resource value: 0x7F070115
			public const int rollText = 2131165461;
			
			// aapt resource value: 0x7F070116
			public const int rollWebView = 2131165462;
			
			// aapt resource value: 0x7F070117
			public const int roundText = 2131165463;
			
			// aapt resource value: 0x7F070118
			public const int rulesButton = 2131165464;
			
			// aapt resource value: 0x7F070119
			public const int rulesImageButton = 2131165465;
			
			// aapt resource value: 0x7F07011A
			public const int saveButton = 2131165466;
			
			// aapt resource value: 0x7F07011B
			public const int savingThrowButton = 2131165467;
			
			// aapt resource value: 0x7F07011C
			public const int schoolButton = 2131165468;
			
			// aapt resource value: 0x7F07011D
			public const int scrollView1 = 2131165469;
			
			// aapt resource value: 0x7F07011E
			public const int searchLayout = 2131165470;
			
			// aapt resource value: 0x7F07011F
			public const int searchReplacementLayout = 2131165471;
			
			// aapt resource value: 0x7F070120
			public const int selectAllButton = 2131165472;
			
			// aapt resource value: 0x7F070121
			public const int sensesText = 2131165473;
			
			// aapt resource value: 0x7F070122
			public const int settingsButton = 2131165474;
			
			// aapt resource value: 0x7F070123
			public const int shieldText = 2131165475;
			
			// aapt resource value: 0x7F070124
			public const int sizeButton = 2131165476;
			
			// aapt resource value: 0x7F070125
			public const int sizeMultiplierButton = 2131165477;
			
			// aapt resource value: 0x7F070126
			public const int skeletonLayout = 2131165478;
			
			// aapt resource value: 0x7F070127
			public const int skillListView = 2131165479;
			
			// aapt resource value: 0x7F070128
			public const int skillsLinearLayout = 2131165480;
			
			// aapt resource value: 0x7F070129
			public const int somaticCheckbox = 2131165481;
			
			// aapt resource value: 0x7F07012A
			public const int sortButton = 2131165482;
			
			// aapt resource value: 0x7F07012B
			public const int spaceText = 2131165483;
			
			// aapt resource value: 0x7F07012C
			public const int specialAttacksText = 2131165484;
			
			// aapt resource value: 0x7F07012D
			public const int specialImageTab = 2131165485;
			
			// aapt resource value: 0x7F07012E
			public const int specialLayout = 2131165486;
			
			// aapt resource value: 0x7F07012F
			public const int specialTab = 2131165487;
			
			// aapt resource value: 0x7F070130
			public const int specialText = 2131165488;
			
			// aapt resource value: 0x7F070131
			public const int speedText = 2131165489;
			
			// aapt resource value: 0x7F070132
			public const int spellLevelListView = 2131165490;
			
			// aapt resource value: 0x7F070133
			public const int spellLikeAbilitiesText = 2131165491;
			
			// aapt resource value: 0x7F070134
			public const int spellResistanceButton = 2131165492;
			
			// aapt resource value: 0x7F070135
			public const int spellsButton = 2131165493;
			
			// aapt resource value: 0x7F070136
			public const int spellsImageButton = 2131165494;
			
			// aapt resource value: 0x7F070137
			public const int spellsKnownText = 2131165495;
			
			// aapt resource value: 0x7F070138
			public const int spellsPreparedText = 2131165496;
			
			// aapt resource value: 0x7F070139
			public const int spellsTabButton = 2131165497;
			
			// aapt resource value: 0x7F07013A
			public const int sqText = 2131165498;
			
			// aapt resource value: 0x7F07013B
			public const int srText = 2131165499;
			
			// aapt resource value: 0x7F07013C
			public const int staffBox = 2131165500;
			
			// aapt resource value: 0x7F07013D
			public const int start = 2131165501;
			
			// aapt resource value: 0x7F07013E
			public const int statChangeButton = 2131165502;
			
			// aapt resource value: 0x7F07013F
			public const int statsImageTab = 2131165503;
			
			// aapt resource value: 0x7F070140
			public const int statsLayout = 2131165504;
			
			// aapt resource value: 0x7F070141
			public const int statsTab = 2131165505;
			
			// aapt resource value: 0x7F070142
			public const int status_bar_latest_event_content = 2131165506;
			
			// aapt resource value: 0x7F070143
			public const int strBox = 2131165507;
			
			// aapt resource value: 0x7F070144
			public const int strText = 2131165508;
			
			// aapt resource value: 0x7F070145
			public const int subschoolButton = 2131165509;
			
			// aapt resource value: 0x7F070146
			public const int subtract10Button = 2131165510;
			
			// aapt resource value: 0x7F070147
			public const int subtract12Button = 2131165511;
			
			// aapt resource value: 0x7F070148
			public const int subtract20Button = 2131165512;
			
			// aapt resource value: 0x7F070149
			public const int subtract4Button = 2131165513;
			
			// aapt resource value: 0x7F07014A
			public const int subtract6Button = 2131165514;
			
			// aapt resource value: 0x7F07014B
			public const int subtract8Button = 2131165515;
			
			// aapt resource value: 0x7F07014D
			public const int subtypesText = 2131165517;
			
			// aapt resource value: 0x7F07014C
			public const int subtypeText = 2131165516;
			
			// aapt resource value: 0x7F07014E
			public const int swimText = 2131165518;
			
			// aapt resource value: 0x7F07014F
			public const int targetsButton = 2131165519;
			
			// aapt resource value: 0x7F070150
			public const int templateButton = 2131165520;
			
			// aapt resource value: 0x7F070151
			public const int templateSelectionLayout = 2131165521;
			
			// aapt resource value: 0x7F070152
			public const int text = 2131165522;
			
			// aapt resource value: 0x7F070153
			public const int text2 = 2131165523;
			
			// aapt resource value: 0x7F070154
			public const int textField = 2131165524;
			
			// aapt resource value: 0x7F070155
			public const int textView1 = 2131165525;
			
			// aapt resource value: 0x7F070156
			public const int textView10 = 2131165526;
			
			// aapt resource value: 0x7F070157
			public const int textView11 = 2131165527;
			
			// aapt resource value: 0x7F070158
			public const int textView12 = 2131165528;
			
			// aapt resource value: 0x7F070159
			public const int textView13 = 2131165529;
			
			// aapt resource value: 0x7F07015A
			public const int textView14 = 2131165530;
			
			// aapt resource value: 0x7F07015B
			public const int textView15 = 2131165531;
			
			// aapt resource value: 0x7F07015C
			public const int textView16 = 2131165532;
			
			// aapt resource value: 0x7F07015D
			public const int textView17 = 2131165533;
			
			// aapt resource value: 0x7F07015E
			public const int textView18 = 2131165534;
			
			// aapt resource value: 0x7F07015F
			public const int textView19 = 2131165535;
			
			// aapt resource value: 0x7F070160
			public const int textView2 = 2131165536;
			
			// aapt resource value: 0x7F070161
			public const int textView20 = 2131165537;
			
			// aapt resource value: 0x7F070162
			public const int textView21 = 2131165538;
			
			// aapt resource value: 0x7F070163
			public const int textView3 = 2131165539;
			
			// aapt resource value: 0x7F070164
			public const int textView4 = 2131165540;
			
			// aapt resource value: 0x7F070165
			public const int textView5 = 2131165541;
			
			// aapt resource value: 0x7F070166
			public const int textView6 = 2131165542;
			
			// aapt resource value: 0x7F070167
			public const int textView7 = 2131165543;
			
			// aapt resource value: 0x7F070168
			public const int textView8 = 2131165544;
			
			// aapt resource value: 0x7F070169
			public const int textView9 = 2131165545;
			
			// aapt resource value: 0x7F07016A
			public const int time = 2131165546;
			
			// aapt resource value: 0x7F07016B
			public const int title = 2131165547;
			
			// aapt resource value: 0x7F07016C
			public const int titleTextView = 2131165548;
			
			// aapt resource value: 0x7F07016D
			public const int top = 2131165549;
			
			// aapt resource value: 0x7F07016E
			public const int touchText = 2131165550;
			
			// aapt resource value: 0x7F07016F
			public const int treasureButton = 2131165551;
			
			// aapt resource value: 0x7F070170
			public const int treasureImageButton = 2131165552;
			
			// aapt resource value: 0x7F070171
			public const int treasureText = 2131165553;
			
			// aapt resource value: 0x7F070172
			public const int typeButton = 2131165554;
			
			// aapt resource value: 0x7F070173
			public const int typesButton = 2131165555;
			
			// aapt resource value: 0x7F070174
			public const int upButton = 2131165556;
			
			// aapt resource value: 0x7F070175
			public const int verbalCheckbox = 2131165557;
			
			// aapt resource value: 0x7F070176
			public const int vertical = 2131165558;
			
			// aapt resource value: 0x7F070177
			public const int visualDescriptionText = 2131165559;
			
			// aapt resource value: 0x7F070178
			public const int wandBox = 2131165560;
			
			// aapt resource value: 0x7F070179
			public const int weaknessLayout = 2131165561;
			
			// aapt resource value: 0x7F07017A
			public const int weaknessText = 2131165562;
			
			// aapt resource value: 0x7F07017B
			public const int webView = 2131165563;
			
			// aapt resource value: 0x7F07017C
			public const int willText = 2131165564;
			
			// aapt resource value: 0x7F07017D
			public const int wisBox = 2131165565;
			
			// aapt resource value: 0x7F07017E
			public const int wisText = 2131165566;
			
			// aapt resource value: 0x7F07017F
			public const int wondrousItemBox = 2131165567;
			
			// aapt resource value: 0x7F070180
			public const int xpText = 2131165568;
			
			// aapt resource value: 0x7F070181
			public const int zombieButton = 2131165569;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F080000
			public const int cancel_button_image_alpha = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int status_bar_notification_info_maxnum = 2131230721;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F090001
			public const int AboutDialog = 2131296257;
			
			// aapt resource value: 0x7F090000
			public const int about_program_dialog_layout = 2131296256;
			
			// aapt resource value: 0x7F090002
			public const int ActionDialog = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int AttacksEditor = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int CharacterList = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int CharacterListItem = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int CheckboxItem = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int Combat = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int ConditionDialog = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int editor_tab_bar = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int FeatDialog = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int FeatPickerDialog = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int FileDialog = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public const int HDDialog = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public const int ImportExportDialog = 2131296270;
			
			// aapt resource value: 0x7F09000F
			public const int Loading = 2131296271;
			
			// aapt resource value: 0x7F090010
			public const int Lookup = 2131296272;
			
			// aapt resource value: 0x7F090011
			public const int Main = 2131296273;
			
			// aapt resource value: 0x7F090012
			public const int MonsterAdvancer = 2131296274;
			
			// aapt resource value: 0x7F090013
			public const int MonsterEditor = 2131296275;
			
			// aapt resource value: 0x7F090014
			public const int MonsterEditorDefense = 2131296276;
			
			// aapt resource value: 0x7F090015
			public const int MonsterEditorDescription = 2131296277;
			
			// aapt resource value: 0x7F090016
			public const int MonsterEditorFeats = 2131296278;
			
			// aapt resource value: 0x7F090017
			public const int MonsterEditorOffense = 2131296279;
			
			// aapt resource value: 0x7F090018
			public const int MonsterEditorOkCancel = 2131296280;
			
			// aapt resource value: 0x7F090019
			public const int MonsterEditorSpecial = 2131296281;
			
			// aapt resource value: 0x7F09001A
			public const int MonsterEditorStats = 2131296282;
			
			// aapt resource value: 0x7F09001B
			public const int MonsterPickerDialog = 2131296283;
			
			// aapt resource value: 0x7F09001C
			public const int MultilineTextDialog = 2131296284;
			
			// aapt resource value: 0x7F09001D
			public const int notification_action = 2131296285;
			
			// aapt resource value: 0x7F09001E
			public const int notification_action_tombstone = 2131296286;
			
			// aapt resource value: 0x7F09001F
			public const int notification_media_action = 2131296287;
			
			// aapt resource value: 0x7F090020
			public const int notification_media_cancel_action = 2131296288;
			
			// aapt resource value: 0x7F090021
			public const int notification_template_big_media = 2131296289;
			
			// aapt resource value: 0x7F090022
			public const int notification_template_big_media_custom = 2131296290;
			
			// aapt resource value: 0x7F090023
			public const int notification_template_big_media_narrow = 2131296291;
			
			// aapt resource value: 0x7F090024
			public const int notification_template_big_media_narrow_custom = 2131296292;
			
			// aapt resource value: 0x7F090025
			public const int notification_template_custom_big = 2131296293;
			
			// aapt resource value: 0x7F090026
			public const int notification_template_icon_group = 2131296294;
			
			// aapt resource value: 0x7F090027
			public const int notification_template_lines_media = 2131296295;
			
			// aapt resource value: 0x7F090028
			public const int notification_template_media = 2131296296;
			
			// aapt resource value: 0x7F090029
			public const int notification_template_media_custom = 2131296297;
			
			// aapt resource value: 0x7F09002A
			public const int notification_template_part_chronometer = 2131296298;
			
			// aapt resource value: 0x7F09002B
			public const int notification_template_part_time = 2131296299;
			
			// aapt resource value: 0x7F09002C
			public const int NumberDialog = 2131296300;
			
			// aapt resource value: 0x7F09002D
			public const int SettingsDialog = 2131296301;
			
			// aapt resource value: 0x7F09002E
			public const int SkillPickerDialog = 2131296302;
			
			// aapt resource value: 0x7F09002F
			public const int SpecialAbility = 2131296303;
			
			// aapt resource value: 0x7F090030
			public const int SpellEditor = 2131296304;
			
			// aapt resource value: 0x7F090031
			public const int SpellLevelItem = 2131296305;
			
			// aapt resource value: 0x7F090032
			public const int TextComboDialog = 2131296306;
			
			// aapt resource value: 0x7F090033
			public const int TextDialog = 2131296307;
			
			// aapt resource value: 0x7F090034
			public const int TreasureGenerator = 2131296308;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0A0000
			public const int app_name = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int hello = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int roll_initiative = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int roll_initiative_short = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int status_bar_notification_info_overflow = 2131361796;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0B0000
			public const int SpellCheckBox = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int SpellText = 2131427329;
			
			// aapt resource value: 0x7F0B0002
			public const int SpellTextOnLight = 2131427330;
			
			// aapt resource value: 0x7F0B0003
			public const int TextAppearance_Compat_Notification = 2131427331;
			
			// aapt resource value: 0x7F0B0004
			public const int TextAppearance_Compat_Notification_Info = 2131427332;
			
			// aapt resource value: 0x7F0B0005
			public const int TextAppearance_Compat_Notification_Info_Media = 2131427333;
			
			// aapt resource value: 0x7F0B0006
			public const int TextAppearance_Compat_Notification_Line2 = 2131427334;
			
			// aapt resource value: 0x7F0B0007
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131427335;
			
			// aapt resource value: 0x7F0B0008
			public const int TextAppearance_Compat_Notification_Media = 2131427336;
			
			// aapt resource value: 0x7F0B0009
			public const int TextAppearance_Compat_Notification_Time = 2131427337;
			
			// aapt resource value: 0x7F0B000A
			public const int TextAppearance_Compat_Notification_Time_Media = 2131427338;
			
			// aapt resource value: 0x7F0B000B
			public const int TextAppearance_Compat_Notification_Title = 2131427339;
			
			// aapt resource value: 0x7F0B000C
			public const int TextAppearance_Compat_Notification_Title_Media = 2131427340;
			
			// aapt resource value: 0x7F0B000D
			public const int Widget_Compat_NotificationActionContainer = 2131427341;
			
			// aapt resource value: 0x7F0B000E
			public const int Widget_Compat_NotificationActionText = 2131427342;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F020003,0x7F020004,0x7F020005,0x7F020006,0x7F020007,0x7F020008 }
			public static int[] FlowLayout = new int[] {
					2130837507,
					2130837508,
					2130837509,
					2130837510,
					2130837511,
					2130837512};
			
			// aapt resource value: 0x0
			public const int FlowLayout_flChildSpacing = 0;
			
			// aapt resource value: 0x1
			public const int FlowLayout_flChildSpacingForLastRow = 1;
			
			// aapt resource value: 0x2
			public const int FlowLayout_flFlow = 2;
			
			// aapt resource value: 0x3
			public const int FlowLayout_flMaxRows = 3;
			
			// aapt resource value: 0x4
			public const int FlowLayout_flRowSpacing = 4;
			
			// aapt resource value: 0x5
			public const int FlowLayout_flRtl = 5;
			
			// aapt resource value: { 0x7F02000A,0x7F02000B,0x7F02000C,0x7F02000D,0x7F02000E,0x7F02000F }
			public static int[] FontFamily = new int[] {
					2130837514,
					2130837515,
					2130837516,
					2130837517,
					2130837518,
					2130837519};
			
			// aapt resource value: { 0x7F020009,0x7F020010,0x7F020011 }
			public static int[] FontFamilyFont = new int[] {
					2130837513,
					2130837520,
					2130837521};
			
			// aapt resource value: 0x0
			public const int FontFamilyFont_font = 0;
			
			// aapt resource value: 0x1
			public const int FontFamilyFont_fontStyle = 1;
			
			// aapt resource value: 0x2
			public const int FontFamilyFont_fontWeight = 2;
			
			// aapt resource value: 0x0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 0x1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 0x2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 0x3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 0x4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 0x5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x7F020000,0x7F020001,0x7F020002,0x7F020019,0x7F02001A,0x7F02001B,0x7F02001C }
			public static int[] GridLayout = new int[] {
					2130837504,
					2130837505,
					2130837506,
					2130837529,
					2130837530,
					2130837531,
					2130837532};
			
			// aapt resource value: 0x0
			public const int GridLayout_alignmentMode = 0;
			
			// aapt resource value: 0x1
			public const int GridLayout_columnCount = 1;
			
			// aapt resource value: 0x2
			public const int GridLayout_columnOrderPreserved = 2;
			
			// aapt resource value: { 0x10100F4,0x10100F5,0x10100F6,0x10100F7,0x10100F8,0x10100F9,0x10100FA,0x7F020012,0x7F020013,0x7F020014,0x7F020015,0x7F020016,0x7F020017,0x7F020018 }
			public static int[] GridLayout_Layout = new int[] {
					16842996,
					16842997,
					16842998,
					16842999,
					16843000,
					16843001,
					16843002,
					2130837522,
					2130837523,
					2130837524,
					2130837525,
					2130837526,
					2130837527,
					2130837528};
			
			// aapt resource value: 0x1
			public const int GridLayout_Layout_android_layout_height = 1;
			
			// aapt resource value: 0x2
			public const int GridLayout_Layout_android_layout_margin = 2;
			
			// aapt resource value: 0x6
			public const int GridLayout_Layout_android_layout_marginBottom = 6;
			
			// aapt resource value: 0x3
			public const int GridLayout_Layout_android_layout_marginLeft = 3;
			
			// aapt resource value: 0x5
			public const int GridLayout_Layout_android_layout_marginRight = 5;
			
			// aapt resource value: 0x4
			public const int GridLayout_Layout_android_layout_marginTop = 4;
			
			// aapt resource value: 0x0
			public const int GridLayout_Layout_android_layout_width = 0;
			
			// aapt resource value: 0x7
			public const int GridLayout_Layout_layout_column = 7;
			
			// aapt resource value: 0x8
			public const int GridLayout_Layout_layout_columnSpan = 8;
			
			// aapt resource value: 0x9
			public const int GridLayout_Layout_layout_columnWeight = 9;
			
			// aapt resource value: 0x10
			public const int GridLayout_Layout_layout_gravity = 16;
			
			// aapt resource value: 0x11
			public const int GridLayout_Layout_layout_row = 17;
			
			// aapt resource value: 0x12
			public const int GridLayout_Layout_layout_rowSpan = 18;
			
			// aapt resource value: 0x13
			public const int GridLayout_Layout_layout_rowWeight = 19;
			
			// aapt resource value: 0x3
			public const int GridLayout_orientation = 3;
			
			// aapt resource value: 0x4
			public const int GridLayout_rowCount = 4;
			
			// aapt resource value: 0x5
			public const int GridLayout_rowOrderPreserved = 5;
			
			// aapt resource value: 0x6
			public const int GridLayout_useDefaultMargins = 6;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
